# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cortex_pb2 as cortex__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CortexServiceStub(object):
    """=== Nodes ===
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNode = channel.unary_unary(
                '/cortex.v1.CortexService/CreateNode',
                request_serializer=cortex__pb2.CreateNodeRequest.SerializeToString,
                response_deserializer=cortex__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/cortex.v1.CortexService/GetNode',
                request_serializer=cortex__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=cortex__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.UpdateNode = channel.unary_unary(
                '/cortex.v1.CortexService/UpdateNode',
                request_serializer=cortex__pb2.UpdateNodeRequest.SerializeToString,
                response_deserializer=cortex__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/cortex.v1.CortexService/DeleteNode',
                request_serializer=cortex__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=cortex__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/cortex.v1.CortexService/ListNodes',
                request_serializer=cortex__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=cortex__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.CreateEdge = channel.unary_unary(
                '/cortex.v1.CortexService/CreateEdge',
                request_serializer=cortex__pb2.CreateEdgeRequest.SerializeToString,
                response_deserializer=cortex__pb2.EdgeResponse.FromString,
                _registered_method=True)
        self.GetEdges = channel.unary_unary(
                '/cortex.v1.CortexService/GetEdges',
                request_serializer=cortex__pb2.GetEdgesRequest.SerializeToString,
                response_deserializer=cortex__pb2.GetEdgesResponse.FromString,
                _registered_method=True)
        self.DeleteEdge = channel.unary_unary(
                '/cortex.v1.CortexService/DeleteEdge',
                request_serializer=cortex__pb2.DeleteEdgeRequest.SerializeToString,
                response_deserializer=cortex__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Traverse = channel.unary_unary(
                '/cortex.v1.CortexService/Traverse',
                request_serializer=cortex__pb2.TraverseRequest.SerializeToString,
                response_deserializer=cortex__pb2.SubgraphResponse.FromString,
                _registered_method=True)
        self.FindPaths = channel.unary_unary(
                '/cortex.v1.CortexService/FindPaths',
                request_serializer=cortex__pb2.FindPathsRequest.SerializeToString,
                response_deserializer=cortex__pb2.PathsResponse.FromString,
                _registered_method=True)
        self.Neighborhood = channel.unary_unary(
                '/cortex.v1.CortexService/Neighborhood',
                request_serializer=cortex__pb2.NeighborhoodRequest.SerializeToString,
                response_deserializer=cortex__pb2.SubgraphResponse.FromString,
                _registered_method=True)
        self.SimilaritySearch = channel.unary_unary(
                '/cortex.v1.CortexService/SimilaritySearch',
                request_serializer=cortex__pb2.SimilaritySearchRequest.SerializeToString,
                response_deserializer=cortex__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/cortex.v1.CortexService/HybridSearch',
                request_serializer=cortex__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=cortex__pb2.HybridSearchResponse.FromString,
                _registered_method=True)
        self.GetBriefing = channel.unary_unary(
                '/cortex.v1.CortexService/GetBriefing',
                request_serializer=cortex__pb2.BriefingRequest.SerializeToString,
                response_deserializer=cortex__pb2.BriefingResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/cortex.v1.CortexService/Stats',
                request_serializer=cortex__pb2.StatsRequest.SerializeToString,
                response_deserializer=cortex__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.AutoLinkerStatus = channel.unary_unary(
                '/cortex.v1.CortexService/AutoLinkerStatus',
                request_serializer=cortex__pb2.AutoLinkerStatusRequest.SerializeToString,
                response_deserializer=cortex__pb2.AutoLinkerStatusResponse.FromString,
                _registered_method=True)
        self.TriggerAutoLink = channel.unary_unary(
                '/cortex.v1.CortexService/TriggerAutoLink',
                request_serializer=cortex__pb2.TriggerAutoLinkRequest.SerializeToString,
                response_deserializer=cortex__pb2.TriggerAutoLinkResponse.FromString,
                _registered_method=True)
        self.Reindex = channel.unary_unary(
                '/cortex.v1.CortexService/Reindex',
                request_serializer=cortex__pb2.ReindexRequest.SerializeToString,
                response_deserializer=cortex__pb2.ReindexResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cortex.v1.CortexService/Health',
                request_serializer=cortex__pb2.HealthRequest.SerializeToString,
                response_deserializer=cortex__pb2.HealthResponse.FromString,
                _registered_method=True)


class CortexServiceServicer(object):
    """=== Nodes ===
    """

    def CreateNode(self, request, context):
        """Create a new knowledge node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Get a node by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNode(self, request, context):
        """Update a node's content (triggers re-embedding).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Soft-delete a node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """List nodes with filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEdge(self, request, context):
        """=== Edges ===

        Create a manual edge between two nodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdges(self, request, context):
        """Get edges for a node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEdge(self, request, context):
        """Delete an edge.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Traverse(self, request, context):
        """=== Graph Queries ===

        Traverse the graph from starting nodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPaths(self, request, context):
        """Find paths between two nodes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Neighborhood(self, request, context):
        """Get node neighborhood (convenience).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimilaritySearch(self, request, context):
        """=== Search ===

        Semantic similarity search.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Hybrid search (vector + graph proximity).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBriefing(self, request, context):
        """=== Briefings ===

        Get a synthesised context briefing for an agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """=== Admin ===

        Get graph statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoLinkerStatus(self, request, context):
        """Get auto-linker metrics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerAutoLink(self, request, context):
        """Trigger manual auto-linker cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reindex(self, request, context):
        """Reindex all embeddings (model change).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CortexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNode,
                    request_deserializer=cortex__pb2.CreateNodeRequest.FromString,
                    response_serializer=cortex__pb2.NodeResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=cortex__pb2.GetNodeRequest.FromString,
                    response_serializer=cortex__pb2.NodeResponse.SerializeToString,
            ),
            'UpdateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNode,
                    request_deserializer=cortex__pb2.UpdateNodeRequest.FromString,
                    response_serializer=cortex__pb2.NodeResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=cortex__pb2.DeleteNodeRequest.FromString,
                    response_serializer=cortex__pb2.DeleteResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=cortex__pb2.ListNodesRequest.FromString,
                    response_serializer=cortex__pb2.ListNodesResponse.SerializeToString,
            ),
            'CreateEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEdge,
                    request_deserializer=cortex__pb2.CreateEdgeRequest.FromString,
                    response_serializer=cortex__pb2.EdgeResponse.SerializeToString,
            ),
            'GetEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdges,
                    request_deserializer=cortex__pb2.GetEdgesRequest.FromString,
                    response_serializer=cortex__pb2.GetEdgesResponse.SerializeToString,
            ),
            'DeleteEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEdge,
                    request_deserializer=cortex__pb2.DeleteEdgeRequest.FromString,
                    response_serializer=cortex__pb2.DeleteResponse.SerializeToString,
            ),
            'Traverse': grpc.unary_unary_rpc_method_handler(
                    servicer.Traverse,
                    request_deserializer=cortex__pb2.TraverseRequest.FromString,
                    response_serializer=cortex__pb2.SubgraphResponse.SerializeToString,
            ),
            'FindPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPaths,
                    request_deserializer=cortex__pb2.FindPathsRequest.FromString,
                    response_serializer=cortex__pb2.PathsResponse.SerializeToString,
            ),
            'Neighborhood': grpc.unary_unary_rpc_method_handler(
                    servicer.Neighborhood,
                    request_deserializer=cortex__pb2.NeighborhoodRequest.FromString,
                    response_serializer=cortex__pb2.SubgraphResponse.SerializeToString,
            ),
            'SimilaritySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SimilaritySearch,
                    request_deserializer=cortex__pb2.SimilaritySearchRequest.FromString,
                    response_serializer=cortex__pb2.SearchResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=cortex__pb2.HybridSearchRequest.FromString,
                    response_serializer=cortex__pb2.HybridSearchResponse.SerializeToString,
            ),
            'GetBriefing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBriefing,
                    request_deserializer=cortex__pb2.BriefingRequest.FromString,
                    response_serializer=cortex__pb2.BriefingResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=cortex__pb2.StatsRequest.FromString,
                    response_serializer=cortex__pb2.StatsResponse.SerializeToString,
            ),
            'AutoLinkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoLinkerStatus,
                    request_deserializer=cortex__pb2.AutoLinkerStatusRequest.FromString,
                    response_serializer=cortex__pb2.AutoLinkerStatusResponse.SerializeToString,
            ),
            'TriggerAutoLink': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerAutoLink,
                    request_deserializer=cortex__pb2.TriggerAutoLinkRequest.FromString,
                    response_serializer=cortex__pb2.TriggerAutoLinkResponse.SerializeToString,
            ),
            'Reindex': grpc.unary_unary_rpc_method_handler(
                    servicer.Reindex,
                    request_deserializer=cortex__pb2.ReindexRequest.FromString,
                    response_serializer=cortex__pb2.ReindexResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cortex__pb2.HealthRequest.FromString,
                    response_serializer=cortex__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortex.v1.CortexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortex.v1.CortexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CortexService(object):
    """=== Nodes ===
    """

    @staticmethod
    def CreateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/CreateNode',
            cortex__pb2.CreateNodeRequest.SerializeToString,
            cortex__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/GetNode',
            cortex__pb2.GetNodeRequest.SerializeToString,
            cortex__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/UpdateNode',
            cortex__pb2.UpdateNodeRequest.SerializeToString,
            cortex__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/DeleteNode',
            cortex__pb2.DeleteNodeRequest.SerializeToString,
            cortex__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/ListNodes',
            cortex__pb2.ListNodesRequest.SerializeToString,
            cortex__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/CreateEdge',
            cortex__pb2.CreateEdgeRequest.SerializeToString,
            cortex__pb2.EdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/GetEdges',
            cortex__pb2.GetEdgesRequest.SerializeToString,
            cortex__pb2.GetEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/DeleteEdge',
            cortex__pb2.DeleteEdgeRequest.SerializeToString,
            cortex__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Traverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/Traverse',
            cortex__pb2.TraverseRequest.SerializeToString,
            cortex__pb2.SubgraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/FindPaths',
            cortex__pb2.FindPathsRequest.SerializeToString,
            cortex__pb2.PathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Neighborhood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/Neighborhood',
            cortex__pb2.NeighborhoodRequest.SerializeToString,
            cortex__pb2.SubgraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimilaritySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/SimilaritySearch',
            cortex__pb2.SimilaritySearchRequest.SerializeToString,
            cortex__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/HybridSearch',
            cortex__pb2.HybridSearchRequest.SerializeToString,
            cortex__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBriefing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/GetBriefing',
            cortex__pb2.BriefingRequest.SerializeToString,
            cortex__pb2.BriefingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/Stats',
            cortex__pb2.StatsRequest.SerializeToString,
            cortex__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoLinkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/AutoLinkerStatus',
            cortex__pb2.AutoLinkerStatusRequest.SerializeToString,
            cortex__pb2.AutoLinkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerAutoLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/TriggerAutoLink',
            cortex__pb2.TriggerAutoLinkRequest.SerializeToString,
            cortex__pb2.TriggerAutoLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reindex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/Reindex',
            cortex__pb2.ReindexRequest.SerializeToString,
            cortex__pb2.ReindexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortex.v1.CortexService/Health',
            cortex__pb2.HealthRequest.SerializeToString,
            cortex__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
