// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cortex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // NodeKind as string
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Importance    float32                `protobuf:"fixed32,6,opt,name=importance,proto3" json:"importance,omitempty"` // 0.0-1.0, default 0.5
	SourceAgent   string                 `protobuf:"bytes,7,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	SourceSession *string                `protobuf:"bytes,8,opt,name=source_session,json=sourceSession,proto3,oneof" json:"source_session,omitempty"`
	SourceChannel *string                `protobuf:"bytes,9,opt,name=source_channel,json=sourceChannel,proto3,oneof" json:"source_channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_cortex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNodeRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateNodeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNodeRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateNodeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateNodeRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateNodeRequest) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *CreateNodeRequest) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *CreateNodeRequest) GetSourceSession() string {
	if x != nil && x.SourceSession != nil {
		return *x.SourceSession
	}
	return ""
}

func (x *CreateNodeRequest) GetSourceChannel() string {
	if x != nil && x.SourceChannel != nil {
		return *x.SourceChannel
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_cortex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Body          *string                `protobuf:"bytes,3,opt,name=body,proto3,oneof" json:"body,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Importance    *float32               `protobuf:"fixed32,6,opt,name=importance,proto3,oneof" json:"importance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_cortex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNodeRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateNodeRequest) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *UpdateNodeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateNodeRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateNodeRequest) GetImportance() float32 {
	if x != nil && x.Importance != nil {
		return *x.Importance
	}
	return 0
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_cortex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cortex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KindFilter    []string               `protobuf:"bytes,1,rep,name=kind_filter,json=kindFilter,proto3" json:"kind_filter,omitempty"`
	TagFilter     []string               `protobuf:"bytes,2,rep,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	SourceAgent   string                 `protobuf:"bytes,3,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	MinImportance float32                `protobuf:"fixed32,4,opt,name=min_importance,json=minImportance,proto3" json:"min_importance,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_cortex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesRequest) GetKindFilter() []string {
	if x != nil {
		return x.KindFilter
	}
	return nil
}

func (x *ListNodesRequest) GetTagFilter() []string {
	if x != nil {
		return x.TagFilter
	}
	return nil
}

func (x *ListNodesRequest) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *ListNodesRequest) GetMinImportance() float32 {
	if x != nil {
		return x.MinImportance
	}
	return 0
}

func (x *ListNodesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNodesRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeResponse        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TotalCount    uint64                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_cortex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*NodeResponse {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Importance    float32                `protobuf:"fixed32,7,opt,name=importance,proto3" json:"importance,omitempty"`
	SourceAgent   string                 `protobuf:"bytes,8,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	SourceSession *string                `protobuf:"bytes,9,opt,name=source_session,json=sourceSession,proto3,oneof" json:"source_session,omitempty"`
	SourceChannel *string                `protobuf:"bytes,10,opt,name=source_channel,json=sourceChannel,proto3,oneof" json:"source_channel,omitempty"`
	AccessCount   uint64                 `protobuf:"varint,11,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	HasEmbedding  bool                   `protobuf:"varint,14,opt,name=has_embedding,json=hasEmbedding,proto3" json:"has_embedding,omitempty"`
	EdgeCount     uint32                 `protobuf:"varint,15,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"` // Total connected edges
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_cortex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{7}
}

func (x *NodeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NodeResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NodeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NodeResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NodeResponse) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *NodeResponse) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *NodeResponse) GetSourceSession() string {
	if x != nil && x.SourceSession != nil {
		return *x.SourceSession
	}
	return ""
}

func (x *NodeResponse) GetSourceChannel() string {
	if x != nil && x.SourceChannel != nil {
		return *x.SourceChannel
	}
	return ""
}

func (x *NodeResponse) GetAccessCount() uint64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *NodeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NodeResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *NodeResponse) GetHasEmbedding() bool {
	if x != nil {
		return x.HasEmbedding
	}
	return false
}

func (x *NodeResponse) GetEdgeCount() uint32 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

type CreateEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"` // Relation as string
	Weight        float32                `protobuf:"fixed32,4,opt,name=weight,proto3" json:"weight,omitempty"`   // Default 1.0 for manual edges
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEdgeRequest) Reset() {
	*x = CreateEdgeRequest{}
	mi := &file_cortex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEdgeRequest) ProtoMessage() {}

func (x *CreateEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEdgeRequest.ProtoReflect.Descriptor instead.
func (*CreateEdgeRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEdgeRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *CreateEdgeRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *CreateEdgeRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CreateEdgeRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type EdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId        string                 `protobuf:"bytes,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Relation      string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Weight        float32                `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeResponse) Reset() {
	*x = EdgeResponse{}
	mi := &file_cortex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeResponse) ProtoMessage() {}

func (x *EdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeResponse.ProtoReflect.Descriptor instead.
func (*EdgeResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{9}
}

func (x *EdgeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EdgeResponse) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *EdgeResponse) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *EdgeResponse) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *EdgeResponse) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EdgeResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EdgeResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetEdgesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"` // "outgoing", "incoming", "both"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgesRequest) Reset() {
	*x = GetEdgesRequest{}
	mi := &file_cortex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgesRequest) ProtoMessage() {}

func (x *GetEdgesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgesRequest.ProtoReflect.Descriptor instead.
func (*GetEdgesRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{10}
}

func (x *GetEdgesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetEdgesRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type GetEdgesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*EdgeResponse        `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEdgesResponse) Reset() {
	*x = GetEdgesResponse{}
	mi := &file_cortex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEdgesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEdgesResponse) ProtoMessage() {}

func (x *GetEdgesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEdgesResponse.ProtoReflect.Descriptor instead.
func (*GetEdgesResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{11}
}

func (x *GetEdgesResponse) GetEdges() []*EdgeResponse {
	if x != nil {
		return x.Edges
	}
	return nil
}

type DeleteEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEdgeRequest) Reset() {
	*x = DeleteEdgeRequest{}
	mi := &file_cortex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEdgeRequest) ProtoMessage() {}

func (x *DeleteEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEdgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEdgeRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteEdgeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TraverseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartIds       []string               `protobuf:"bytes,1,rep,name=start_ids,json=startIds,proto3" json:"start_ids,omitempty"`
	MaxDepth       uint32                 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // 0 = start only
	Direction      string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`                // "outgoing", "incoming", "both"
	RelationFilter []string               `protobuf:"bytes,4,rep,name=relation_filter,json=relationFilter,proto3" json:"relation_filter,omitempty"`
	KindFilter     []string               `protobuf:"bytes,5,rep,name=kind_filter,json=kindFilter,proto3" json:"kind_filter,omitempty"`
	MinWeight      float32                `protobuf:"fixed32,6,opt,name=min_weight,json=minWeight,proto3" json:"min_weight,omitempty"`
	Limit          uint32                 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Strategy       string                 `protobuf:"bytes,8,opt,name=strategy,proto3" json:"strategy,omitempty"` // "bfs", "dfs", "weighted"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TraverseRequest) Reset() {
	*x = TraverseRequest{}
	mi := &file_cortex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraverseRequest) ProtoMessage() {}

func (x *TraverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraverseRequest.ProtoReflect.Descriptor instead.
func (*TraverseRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{13}
}

func (x *TraverseRequest) GetStartIds() []string {
	if x != nil {
		return x.StartIds
	}
	return nil
}

func (x *TraverseRequest) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *TraverseRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *TraverseRequest) GetRelationFilter() []string {
	if x != nil {
		return x.RelationFilter
	}
	return nil
}

func (x *TraverseRequest) GetKindFilter() []string {
	if x != nil {
		return x.KindFilter
	}
	return nil
}

func (x *TraverseRequest) GetMinWeight() float32 {
	if x != nil {
		return x.MinWeight
	}
	return 0
}

func (x *TraverseRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TraverseRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type SubgraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeResponse        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*EdgeResponse        `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	Depths        map[string]uint32      `protobuf:"bytes,3,rep,name=depths,proto3" json:"depths,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // node_id → depth
	VisitedCount  uint32                 `protobuf:"varint,4,opt,name=visited_count,json=visitedCount,proto3" json:"visited_count,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubgraphResponse) Reset() {
	*x = SubgraphResponse{}
	mi := &file_cortex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubgraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubgraphResponse) ProtoMessage() {}

func (x *SubgraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubgraphResponse.ProtoReflect.Descriptor instead.
func (*SubgraphResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{14}
}

func (x *SubgraphResponse) GetNodes() []*NodeResponse {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *SubgraphResponse) GetEdges() []*EdgeResponse {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *SubgraphResponse) GetDepths() map[string]uint32 {
	if x != nil {
		return x.Depths
	}
	return nil
}

func (x *SubgraphResponse) GetVisitedCount() uint32 {
	if x != nil {
		return x.VisitedCount
	}
	return 0
}

func (x *SubgraphResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type FindPathsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	MaxPaths      uint32                 `protobuf:"varint,3,opt,name=max_paths,json=maxPaths,proto3" json:"max_paths,omitempty"` // Default 1 (shortest path)
	MaxDepth      uint32                 `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // Optional depth limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPathsRequest) Reset() {
	*x = FindPathsRequest{}
	mi := &file_cortex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPathsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPathsRequest) ProtoMessage() {}

func (x *FindPathsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPathsRequest.ProtoReflect.Descriptor instead.
func (*FindPathsRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{15}
}

func (x *FindPathsRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *FindPathsRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *FindPathsRequest) GetMaxPaths() uint32 {
	if x != nil {
		return x.MaxPaths
	}
	return 0
}

func (x *FindPathsRequest) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type PathsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*PathEntry           `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathsResponse) Reset() {
	*x = PathsResponse{}
	mi := &file_cortex_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathsResponse) ProtoMessage() {}

func (x *PathsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathsResponse.ProtoReflect.Descriptor instead.
func (*PathsResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{16}
}

func (x *PathsResponse) GetPaths() []*PathEntry {
	if x != nil {
		return x.Paths
	}
	return nil
}

type PathEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	TotalWeight   float32                `protobuf:"fixed32,2,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	Length        uint32                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathEntry) Reset() {
	*x = PathEntry{}
	mi := &file_cortex_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathEntry) ProtoMessage() {}

func (x *PathEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathEntry.ProtoReflect.Descriptor instead.
func (*PathEntry) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{17}
}

func (x *PathEntry) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

func (x *PathEntry) GetTotalWeight() float32 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *PathEntry) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type NeighborhoodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Depth         uint32                 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`        // Default 1
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"` // Default "both"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeighborhoodRequest) Reset() {
	*x = NeighborhoodRequest{}
	mi := &file_cortex_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeighborhoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborhoodRequest) ProtoMessage() {}

func (x *NeighborhoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborhoodRequest.ProtoReflect.Descriptor instead.
func (*NeighborhoodRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{18}
}

func (x *NeighborhoodRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NeighborhoodRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *NeighborhoodRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type SimilaritySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Default 10
	KindFilter    []string               `protobuf:"bytes,3,rep,name=kind_filter,json=kindFilter,proto3" json:"kind_filter,omitempty"`
	MinScore      float32                `protobuf:"fixed32,4,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"` // Default 0.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilaritySearchRequest) Reset() {
	*x = SimilaritySearchRequest{}
	mi := &file_cortex_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilaritySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilaritySearchRequest) ProtoMessage() {}

func (x *SimilaritySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilaritySearchRequest.ProtoReflect.Descriptor instead.
func (*SimilaritySearchRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{19}
}

func (x *SimilaritySearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SimilaritySearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SimilaritySearchRequest) GetKindFilter() []string {
	if x != nil {
		return x.KindFilter
	}
	return nil
}

func (x *SimilaritySearchRequest) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultEntry   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_cortex_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{20}
}

func (x *SearchResponse) GetResults() []*SearchResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResultEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeResponse          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultEntry) Reset() {
	*x = SearchResultEntry{}
	mi := &file_cortex_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultEntry) ProtoMessage() {}

func (x *SearchResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultEntry.ProtoReflect.Descriptor instead.
func (*SearchResultEntry) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{21}
}

func (x *SearchResultEntry) GetNode() *NodeResponse {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SearchResultEntry) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type HybridSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	AnchorIds      []string               `protobuf:"bytes,2,rep,name=anchor_ids,json=anchorIds,proto3" json:"anchor_ids,omitempty"`
	VectorWeight   float32                `protobuf:"fixed32,3,opt,name=vector_weight,json=vectorWeight,proto3" json:"vector_weight,omitempty"` // Default 0.7
	Limit          uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	KindFilter     []string               `protobuf:"bytes,5,rep,name=kind_filter,json=kindFilter,proto3" json:"kind_filter,omitempty"`
	MaxAnchorDepth uint32                 `protobuf:"varint,6,opt,name=max_anchor_depth,json=maxAnchorDepth,proto3" json:"max_anchor_depth,omitempty"` // Default 3
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_cortex_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{22}
}

func (x *HybridSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HybridSearchRequest) GetAnchorIds() []string {
	if x != nil {
		return x.AnchorIds
	}
	return nil
}

func (x *HybridSearchRequest) GetVectorWeight() float32 {
	if x != nil {
		return x.VectorWeight
	}
	return 0
}

func (x *HybridSearchRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HybridSearchRequest) GetKindFilter() []string {
	if x != nil {
		return x.KindFilter
	}
	return nil
}

func (x *HybridSearchRequest) GetMaxAnchorDepth() uint32 {
	if x != nil {
		return x.MaxAnchorDepth
	}
	return 0
}

type HybridSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*HybridResultEntry   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchResponse) Reset() {
	*x = HybridSearchResponse{}
	mi := &file_cortex_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchResponse) ProtoMessage() {}

func (x *HybridSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{23}
}

func (x *HybridSearchResponse) GetResults() []*HybridResultEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type HybridResultEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Node               *NodeResponse          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	VectorScore        float32                `protobuf:"fixed32,2,opt,name=vector_score,json=vectorScore,proto3" json:"vector_score,omitempty"`
	GraphScore         float32                `protobuf:"fixed32,3,opt,name=graph_score,json=graphScore,proto3" json:"graph_score,omitempty"`
	CombinedScore      float32                `protobuf:"fixed32,4,opt,name=combined_score,json=combinedScore,proto3" json:"combined_score,omitempty"`
	NearestAnchorId    *string                `protobuf:"bytes,5,opt,name=nearest_anchor_id,json=nearestAnchorId,proto3,oneof" json:"nearest_anchor_id,omitempty"`
	NearestAnchorDepth *uint32                `protobuf:"varint,6,opt,name=nearest_anchor_depth,json=nearestAnchorDepth,proto3,oneof" json:"nearest_anchor_depth,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HybridResultEntry) Reset() {
	*x = HybridResultEntry{}
	mi := &file_cortex_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridResultEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridResultEntry) ProtoMessage() {}

func (x *HybridResultEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridResultEntry.ProtoReflect.Descriptor instead.
func (*HybridResultEntry) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{24}
}

func (x *HybridResultEntry) GetNode() *NodeResponse {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HybridResultEntry) GetVectorScore() float32 {
	if x != nil {
		return x.VectorScore
	}
	return 0
}

func (x *HybridResultEntry) GetGraphScore() float32 {
	if x != nil {
		return x.GraphScore
	}
	return 0
}

func (x *HybridResultEntry) GetCombinedScore() float32 {
	if x != nil {
		return x.CombinedScore
	}
	return 0
}

func (x *HybridResultEntry) GetNearestAnchorId() string {
	if x != nil && x.NearestAnchorId != nil {
		return *x.NearestAnchorId
	}
	return ""
}

func (x *HybridResultEntry) GetNearestAnchorDepth() uint32 {
	if x != nil && x.NearestAnchorDepth != nil {
		return *x.NearestAnchorDepth
	}
	return 0
}

type BriefingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // e.g. "kai", "dutybound"
	Compact       bool                   `protobuf:"varint,2,opt,name=compact,proto3" json:"compact,omitempty"`               // Use compact renderer (~4× density)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BriefingRequest) Reset() {
	*x = BriefingRequest{}
	mi := &file_cortex_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefingRequest) ProtoMessage() {}

func (x *BriefingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefingRequest.ProtoReflect.Descriptor instead.
func (*BriefingRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{25}
}

func (x *BriefingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BriefingRequest) GetCompact() bool {
	if x != nil {
		return x.Compact
	}
	return false
}

type BriefingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Rendered       string                 `protobuf:"bytes,2,opt,name=rendered,proto3" json:"rendered,omitempty"` // Rendered markdown/compact text
	Sections       []*BriefingSection     `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"`
	GeneratedAt    string                 `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // ISO-8601 timestamp string
	NodesConsulted uint32                 `protobuf:"varint,5,opt,name=nodes_consulted,json=nodesConsulted,proto3" json:"nodes_consulted,omitempty"`
	Cached         bool                   `protobuf:"varint,6,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BriefingResponse) Reset() {
	*x = BriefingResponse{}
	mi := &file_cortex_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefingResponse) ProtoMessage() {}

func (x *BriefingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefingResponse.ProtoReflect.Descriptor instead.
func (*BriefingResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{26}
}

func (x *BriefingResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BriefingResponse) GetRendered() string {
	if x != nil {
		return x.Rendered
	}
	return ""
}

func (x *BriefingResponse) GetSections() []*BriefingSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *BriefingResponse) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *BriefingResponse) GetNodesConsulted() uint32 {
	if x != nil {
		return x.NodesConsulted
	}
	return 0
}

func (x *BriefingResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

type BriefingSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"` // e.g. "Identity & Preferences", "Patterns"
	Nodes         []*NodeResponse        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BriefingSection) Reset() {
	*x = BriefingSection{}
	mi := &file_cortex_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BriefingSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BriefingSection) ProtoMessage() {}

func (x *BriefingSection) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BriefingSection.ProtoReflect.Descriptor instead.
func (*BriefingSection) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{27}
}

func (x *BriefingSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BriefingSection) GetNodes() []*NodeResponse {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_cortex_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{28}
}

type StatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeCount       uint64                 `protobuf:"varint,1,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	EdgeCount       uint64                 `protobuf:"varint,2,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	NodesByKind     map[string]uint64      `protobuf:"bytes,3,rep,name=nodes_by_kind,json=nodesByKind,proto3" json:"nodes_by_kind,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EdgesByRelation map[string]uint64      `protobuf:"bytes,4,rep,name=edges_by_relation,json=edgesByRelation,proto3" json:"edges_by_relation,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DbSizeBytes     uint64                 `protobuf:"varint,5,opt,name=db_size_bytes,json=dbSizeBytes,proto3" json:"db_size_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_cortex_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{29}
}

func (x *StatsResponse) GetNodeCount() uint64 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *StatsResponse) GetEdgeCount() uint64 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *StatsResponse) GetNodesByKind() map[string]uint64 {
	if x != nil {
		return x.NodesByKind
	}
	return nil
}

func (x *StatsResponse) GetEdgesByRelation() map[string]uint64 {
	if x != nil {
		return x.EdgesByRelation
	}
	return nil
}

func (x *StatsResponse) GetDbSizeBytes() uint64 {
	if x != nil {
		return x.DbSizeBytes
	}
	return 0
}

type AutoLinkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoLinkerStatusRequest) Reset() {
	*x = AutoLinkerStatusRequest{}
	mi := &file_cortex_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoLinkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoLinkerStatusRequest) ProtoMessage() {}

func (x *AutoLinkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoLinkerStatusRequest.ProtoReflect.Descriptor instead.
func (*AutoLinkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{30}
}

type AutoLinkerStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Cycles              uint64                 `protobuf:"varint,1,opt,name=cycles,proto3" json:"cycles,omitempty"`
	NodesProcessed      uint64                 `protobuf:"varint,2,opt,name=nodes_processed,json=nodesProcessed,proto3" json:"nodes_processed,omitempty"`
	EdgesCreated        uint64                 `protobuf:"varint,3,opt,name=edges_created,json=edgesCreated,proto3" json:"edges_created,omitempty"`
	EdgesPruned         uint64                 `protobuf:"varint,4,opt,name=edges_pruned,json=edgesPruned,proto3" json:"edges_pruned,omitempty"`
	EdgesDeleted        uint64                 `protobuf:"varint,5,opt,name=edges_deleted,json=edgesDeleted,proto3" json:"edges_deleted,omitempty"`
	DuplicatesFound     uint64                 `protobuf:"varint,6,opt,name=duplicates_found,json=duplicatesFound,proto3" json:"duplicates_found,omitempty"`
	ContradictionsFound uint64                 `protobuf:"varint,7,opt,name=contradictions_found,json=contradictionsFound,proto3" json:"contradictions_found,omitempty"`
	LastCycleDurationMs uint64                 `protobuf:"varint,8,opt,name=last_cycle_duration_ms,json=lastCycleDurationMs,proto3" json:"last_cycle_duration_ms,omitempty"`
	Cursor              *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=cursor,proto3" json:"cursor,omitempty"`
	BacklogSize         uint64                 `protobuf:"varint,10,opt,name=backlog_size,json=backlogSize,proto3" json:"backlog_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AutoLinkerStatusResponse) Reset() {
	*x = AutoLinkerStatusResponse{}
	mi := &file_cortex_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoLinkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoLinkerStatusResponse) ProtoMessage() {}

func (x *AutoLinkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoLinkerStatusResponse.ProtoReflect.Descriptor instead.
func (*AutoLinkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{31}
}

func (x *AutoLinkerStatusResponse) GetCycles() uint64 {
	if x != nil {
		return x.Cycles
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetNodesProcessed() uint64 {
	if x != nil {
		return x.NodesProcessed
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetEdgesCreated() uint64 {
	if x != nil {
		return x.EdgesCreated
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetEdgesPruned() uint64 {
	if x != nil {
		return x.EdgesPruned
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetEdgesDeleted() uint64 {
	if x != nil {
		return x.EdgesDeleted
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetDuplicatesFound() uint64 {
	if x != nil {
		return x.DuplicatesFound
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetContradictionsFound() uint64 {
	if x != nil {
		return x.ContradictionsFound
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetLastCycleDurationMs() uint64 {
	if x != nil {
		return x.LastCycleDurationMs
	}
	return 0
}

func (x *AutoLinkerStatusResponse) GetCursor() *timestamppb.Timestamp {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *AutoLinkerStatusResponse) GetBacklogSize() uint64 {
	if x != nil {
		return x.BacklogSize
	}
	return 0
}

type TriggerAutoLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerAutoLinkRequest) Reset() {
	*x = TriggerAutoLinkRequest{}
	mi := &file_cortex_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerAutoLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAutoLinkRequest) ProtoMessage() {}

func (x *TriggerAutoLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAutoLinkRequest.ProtoReflect.Descriptor instead.
func (*TriggerAutoLinkRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{32}
}

type TriggerAutoLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerAutoLinkResponse) Reset() {
	*x = TriggerAutoLinkResponse{}
	mi := &file_cortex_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerAutoLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerAutoLinkResponse) ProtoMessage() {}

func (x *TriggerAutoLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerAutoLinkResponse.ProtoReflect.Descriptor instead.
func (*TriggerAutoLinkResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{33}
}

func (x *TriggerAutoLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerAutoLinkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReindexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexRequest) Reset() {
	*x = ReindexRequest{}
	mi := &file_cortex_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexRequest) ProtoMessage() {}

func (x *ReindexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexRequest.ProtoReflect.Descriptor instead.
func (*ReindexRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{34}
}

type ReindexResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodesReindexed uint64                 `protobuf:"varint,2,opt,name=nodes_reindexed,json=nodesReindexed,proto3" json:"nodes_reindexed,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReindexResponse) Reset() {
	*x = ReindexResponse{}
	mi := &file_cortex_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexResponse) ProtoMessage() {}

func (x *ReindexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexResponse.ProtoReflect.Descriptor instead.
func (*ReindexResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{35}
}

func (x *ReindexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReindexResponse) GetNodesReindexed() uint64 {
	if x != nil {
		return x.NodesReindexed
	}
	return 0
}

func (x *ReindexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cortex_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{36}
}

type HealthResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Healthy       bool                      `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                    `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds uint64                    `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Stats         *StatsResponse            `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	AutoLinker    *AutoLinkerStatusResponse `protobuf:"bytes,5,opt,name=auto_linker,json=autoLinker,proto3" json:"auto_linker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_cortex_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortex_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_cortex_proto_rawDescGZIP(), []int{37}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetStats() *StatsResponse {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *HealthResponse) GetAutoLinker() *AutoLinkerStatusResponse {
	if x != nil {
		return x.AutoLinker
	}
	return nil
}

var File_cortex_proto protoreflect.FileDescriptor

const file_cortex_proto_rawDesc = "" +
	"\n" +
	"\fcortex.proto\x12\tcortex.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x03\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.cortex.v1.CreateNodeRequest.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"importance\x18\x06 \x01(\x02R\n" +
	"importance\x12!\n" +
	"\fsource_agent\x18\a \x01(\tR\vsourceAgent\x12*\n" +
	"\x0esource_session\x18\b \x01(\tH\x00R\rsourceSession\x88\x01\x01\x12*\n" +
	"\x0esource_channel\x18\t \x01(\tH\x01R\rsourceChannel\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_source_sessionB\x11\n" +
	"\x0f_source_channel\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x02\n" +
	"\x11UpdateNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x17\n" +
	"\x04body\x18\x03 \x01(\tH\x01R\x04body\x88\x01\x01\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.cortex.v1.UpdateNodeRequest.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12#\n" +
	"\n" +
	"importance\x18\x06 \x01(\x02H\x02R\n" +
	"importance\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_titleB\a\n" +
	"\x05_bodyB\r\n" +
	"\v_importance\"#\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xca\x01\n" +
	"\x10ListNodesRequest\x12\x1f\n" +
	"\vkind_filter\x18\x01 \x03(\tR\n" +
	"kindFilter\x12\x1d\n" +
	"\n" +
	"tag_filter\x18\x02 \x03(\tR\ttagFilter\x12!\n" +
	"\fsource_agent\x18\x03 \x01(\tR\vsourceAgent\x12%\n" +
	"\x0emin_importance\x18\x04 \x01(\x02R\rminImportance\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\rR\x06offset\"c\n" +
	"\x11ListNodesResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.cortex.v1.NodeResponseR\x05nodes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x04R\n" +
	"totalCount\"\x8e\x05\n" +
	"\fNodeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.cortex.v1.NodeResponse.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"importance\x18\a \x01(\x02R\n" +
	"importance\x12!\n" +
	"\fsource_agent\x18\b \x01(\tR\vsourceAgent\x12*\n" +
	"\x0esource_session\x18\t \x01(\tH\x00R\rsourceSession\x88\x01\x01\x12*\n" +
	"\x0esource_channel\x18\n" +
	" \x01(\tH\x01R\rsourceChannel\x88\x01\x01\x12!\n" +
	"\faccess_count\x18\v \x01(\x04R\vaccessCount\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12#\n" +
	"\rhas_embedding\x18\x0e \x01(\bR\fhasEmbedding\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x0f \x01(\rR\tedgeCount\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_source_sessionB\x11\n" +
	"\x0f_source_channel\"u\n" +
	"\x11CreateEdgeRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x02R\x06weight\"\xf6\x01\n" +
	"\fEdgeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x02R\x06weight\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"H\n" +
	"\x0fGetEdgesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\"A\n" +
	"\x10GetEdgesResponse\x12-\n" +
	"\x05edges\x18\x01 \x03(\v2\x17.cortex.v1.EdgeResponseR\x05edges\"#\n" +
	"\x11DeleteEdgeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x84\x02\n" +
	"\x0fTraverseRequest\x12\x1b\n" +
	"\tstart_ids\x18\x01 \x03(\tR\bstartIds\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\rR\bmaxDepth\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12'\n" +
	"\x0frelation_filter\x18\x04 \x03(\tR\x0erelationFilter\x12\x1f\n" +
	"\vkind_filter\x18\x05 \x03(\tR\n" +
	"kindFilter\x12\x1d\n" +
	"\n" +
	"min_weight\x18\x06 \x01(\x02R\tminWeight\x12\x14\n" +
	"\x05limit\x18\a \x01(\rR\x05limit\x12\x1a\n" +
	"\bstrategy\x18\b \x01(\tR\bstrategy\"\xaf\x02\n" +
	"\x10SubgraphResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.cortex.v1.NodeResponseR\x05nodes\x12-\n" +
	"\x05edges\x18\x02 \x03(\v2\x17.cortex.v1.EdgeResponseR\x05edges\x12?\n" +
	"\x06depths\x18\x03 \x03(\v2'.cortex.v1.SubgraphResponse.DepthsEntryR\x06depths\x12#\n" +
	"\rvisited_count\x18\x04 \x01(\rR\fvisitedCount\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x1a9\n" +
	"\vDepthsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"z\n" +
	"\x10FindPathsRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x1b\n" +
	"\tmax_paths\x18\x03 \x01(\rR\bmaxPaths\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\rR\bmaxDepth\";\n" +
	"\rPathsResponse\x12*\n" +
	"\x05paths\x18\x01 \x03(\v2\x14.cortex.v1.PathEntryR\x05paths\"a\n" +
	"\tPathEntry\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\x12!\n" +
	"\ftotal_weight\x18\x02 \x01(\x02R\vtotalWeight\x12\x16\n" +
	"\x06length\x18\x03 \x01(\rR\x06length\"b\n" +
	"\x13NeighborhoodRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\rR\x05depth\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\"\x83\x01\n" +
	"\x17SimilaritySearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1f\n" +
	"\vkind_filter\x18\x03 \x03(\tR\n" +
	"kindFilter\x12\x1b\n" +
	"\tmin_score\x18\x04 \x01(\x02R\bminScore\"H\n" +
	"\x0eSearchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.cortex.v1.SearchResultEntryR\aresults\"V\n" +
	"\x11SearchResultEntry\x12+\n" +
	"\x04node\x18\x01 \x01(\v2\x17.cortex.v1.NodeResponseR\x04node\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"\xd0\x01\n" +
	"\x13HybridSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"anchor_ids\x18\x02 \x03(\tR\tanchorIds\x12#\n" +
	"\rvector_weight\x18\x03 \x01(\x02R\fvectorWeight\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\x12\x1f\n" +
	"\vkind_filter\x18\x05 \x03(\tR\n" +
	"kindFilter\x12(\n" +
	"\x10max_anchor_depth\x18\x06 \x01(\rR\x0emaxAnchorDepth\"N\n" +
	"\x14HybridSearchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.cortex.v1.HybridResultEntryR\aresults\"\xc2\x02\n" +
	"\x11HybridResultEntry\x12+\n" +
	"\x04node\x18\x01 \x01(\v2\x17.cortex.v1.NodeResponseR\x04node\x12!\n" +
	"\fvector_score\x18\x02 \x01(\x02R\vvectorScore\x12\x1f\n" +
	"\vgraph_score\x18\x03 \x01(\x02R\n" +
	"graphScore\x12%\n" +
	"\x0ecombined_score\x18\x04 \x01(\x02R\rcombinedScore\x12/\n" +
	"\x11nearest_anchor_id\x18\x05 \x01(\tH\x00R\x0fnearestAnchorId\x88\x01\x01\x125\n" +
	"\x14nearest_anchor_depth\x18\x06 \x01(\rH\x01R\x12nearestAnchorDepth\x88\x01\x01B\x14\n" +
	"\x12_nearest_anchor_idB\x17\n" +
	"\x15_nearest_anchor_depth\"F\n" +
	"\x0fBriefingRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acompact\x18\x02 \x01(\bR\acompact\"\xe5\x01\n" +
	"\x10BriefingResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\brendered\x18\x02 \x01(\tR\brendered\x126\n" +
	"\bsections\x18\x03 \x03(\v2\x1a.cortex.v1.BriefingSectionR\bsections\x12!\n" +
	"\fgenerated_at\x18\x04 \x01(\tR\vgeneratedAt\x12'\n" +
	"\x0fnodes_consulted\x18\x05 \x01(\rR\x0enodesConsulted\x12\x16\n" +
	"\x06cached\x18\x06 \x01(\bR\x06cached\"V\n" +
	"\x0fBriefingSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12-\n" +
	"\x05nodes\x18\x02 \x03(\v2\x17.cortex.v1.NodeResponseR\x05nodes\"\x0e\n" +
	"\fStatsRequest\"\x9f\x03\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"node_count\x18\x01 \x01(\x04R\tnodeCount\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x02 \x01(\x04R\tedgeCount\x12M\n" +
	"\rnodes_by_kind\x18\x03 \x03(\v2).cortex.v1.StatsResponse.NodesByKindEntryR\vnodesByKind\x12Y\n" +
	"\x11edges_by_relation\x18\x04 \x03(\v2-.cortex.v1.StatsResponse.EdgesByRelationEntryR\x0fedgesByRelation\x12\"\n" +
	"\rdb_size_bytes\x18\x05 \x01(\x04R\vdbSizeBytes\x1a>\n" +
	"\x10NodesByKindEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aB\n" +
	"\x14EdgesByRelationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x19\n" +
	"\x17AutoLinkerStatusRequest\"\xb2\x03\n" +
	"\x18AutoLinkerStatusResponse\x12\x16\n" +
	"\x06cycles\x18\x01 \x01(\x04R\x06cycles\x12'\n" +
	"\x0fnodes_processed\x18\x02 \x01(\x04R\x0enodesProcessed\x12#\n" +
	"\redges_created\x18\x03 \x01(\x04R\fedgesCreated\x12!\n" +
	"\fedges_pruned\x18\x04 \x01(\x04R\vedgesPruned\x12#\n" +
	"\redges_deleted\x18\x05 \x01(\x04R\fedgesDeleted\x12)\n" +
	"\x10duplicates_found\x18\x06 \x01(\x04R\x0fduplicatesFound\x121\n" +
	"\x14contradictions_found\x18\a \x01(\x04R\x13contradictionsFound\x123\n" +
	"\x16last_cycle_duration_ms\x18\b \x01(\x04R\x13lastCycleDurationMs\x122\n" +
	"\x06cursor\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06cursor\x12!\n" +
	"\fbacklog_size\x18\n" +
	" \x01(\x04R\vbacklogSize\"\x18\n" +
	"\x16TriggerAutoLinkRequest\"M\n" +
	"\x17TriggerAutoLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eReindexRequest\"n\n" +
	"\x0fReindexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnodes_reindexed\x18\x02 \x01(\x04R\x0enodesReindexed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"\xe1\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x12.\n" +
	"\x05stats\x18\x04 \x01(\v2\x18.cortex.v1.StatsResponseR\x05stats\x12D\n" +
	"\vauto_linker\x18\x05 \x01(\v2#.cortex.v1.AutoLinkerStatusResponseR\n" +
	"autoLinker2\xee\n" +
	"\n" +
	"\rCortexService\x12C\n" +
	"\n" +
	"CreateNode\x12\x1c.cortex.v1.CreateNodeRequest\x1a\x17.cortex.v1.NodeResponse\x12=\n" +
	"\aGetNode\x12\x19.cortex.v1.GetNodeRequest\x1a\x17.cortex.v1.NodeResponse\x12C\n" +
	"\n" +
	"UpdateNode\x12\x1c.cortex.v1.UpdateNodeRequest\x1a\x17.cortex.v1.NodeResponse\x12E\n" +
	"\n" +
	"DeleteNode\x12\x1c.cortex.v1.DeleteNodeRequest\x1a\x19.cortex.v1.DeleteResponse\x12F\n" +
	"\tListNodes\x12\x1b.cortex.v1.ListNodesRequest\x1a\x1c.cortex.v1.ListNodesResponse\x12C\n" +
	"\n" +
	"CreateEdge\x12\x1c.cortex.v1.CreateEdgeRequest\x1a\x17.cortex.v1.EdgeResponse\x12C\n" +
	"\bGetEdges\x12\x1a.cortex.v1.GetEdgesRequest\x1a\x1b.cortex.v1.GetEdgesResponse\x12E\n" +
	"\n" +
	"DeleteEdge\x12\x1c.cortex.v1.DeleteEdgeRequest\x1a\x19.cortex.v1.DeleteResponse\x12C\n" +
	"\bTraverse\x12\x1a.cortex.v1.TraverseRequest\x1a\x1b.cortex.v1.SubgraphResponse\x12B\n" +
	"\tFindPaths\x12\x1b.cortex.v1.FindPathsRequest\x1a\x18.cortex.v1.PathsResponse\x12K\n" +
	"\fNeighborhood\x12\x1e.cortex.v1.NeighborhoodRequest\x1a\x1b.cortex.v1.SubgraphResponse\x12Q\n" +
	"\x10SimilaritySearch\x12\".cortex.v1.SimilaritySearchRequest\x1a\x19.cortex.v1.SearchResponse\x12O\n" +
	"\fHybridSearch\x12\x1e.cortex.v1.HybridSearchRequest\x1a\x1f.cortex.v1.HybridSearchResponse\x12F\n" +
	"\vGetBriefing\x12\x1a.cortex.v1.BriefingRequest\x1a\x1b.cortex.v1.BriefingResponse\x12:\n" +
	"\x05Stats\x12\x17.cortex.v1.StatsRequest\x1a\x18.cortex.v1.StatsResponse\x12[\n" +
	"\x10AutoLinkerStatus\x12\".cortex.v1.AutoLinkerStatusRequest\x1a#.cortex.v1.AutoLinkerStatusResponse\x12X\n" +
	"\x0fTriggerAutoLink\x12!.cortex.v1.TriggerAutoLinkRequest\x1a\".cortex.v1.TriggerAutoLinkResponse\x12@\n" +
	"\aReindex\x12\x19.cortex.v1.ReindexRequest\x1a\x1a.cortex.v1.ReindexResponse\x12=\n" +
	"\x06Health\x12\x18.cortex.v1.HealthRequest\x1a\x19.cortex.v1.HealthResponseb\x06proto3"

var (
	file_cortex_proto_rawDescOnce sync.Once
	file_cortex_proto_rawDescData []byte
)

func file_cortex_proto_rawDescGZIP() []byte {
	file_cortex_proto_rawDescOnce.Do(func() {
		file_cortex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortex_proto_rawDesc), len(file_cortex_proto_rawDesc)))
	})
	return file_cortex_proto_rawDescData
}

var file_cortex_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_cortex_proto_goTypes = []any{
	(*CreateNodeRequest)(nil),        // 0: cortex.v1.CreateNodeRequest
	(*GetNodeRequest)(nil),           // 1: cortex.v1.GetNodeRequest
	(*UpdateNodeRequest)(nil),        // 2: cortex.v1.UpdateNodeRequest
	(*DeleteNodeRequest)(nil),        // 3: cortex.v1.DeleteNodeRequest
	(*DeleteResponse)(nil),           // 4: cortex.v1.DeleteResponse
	(*ListNodesRequest)(nil),         // 5: cortex.v1.ListNodesRequest
	(*ListNodesResponse)(nil),        // 6: cortex.v1.ListNodesResponse
	(*NodeResponse)(nil),             // 7: cortex.v1.NodeResponse
	(*CreateEdgeRequest)(nil),        // 8: cortex.v1.CreateEdgeRequest
	(*EdgeResponse)(nil),             // 9: cortex.v1.EdgeResponse
	(*GetEdgesRequest)(nil),          // 10: cortex.v1.GetEdgesRequest
	(*GetEdgesResponse)(nil),         // 11: cortex.v1.GetEdgesResponse
	(*DeleteEdgeRequest)(nil),        // 12: cortex.v1.DeleteEdgeRequest
	(*TraverseRequest)(nil),          // 13: cortex.v1.TraverseRequest
	(*SubgraphResponse)(nil),         // 14: cortex.v1.SubgraphResponse
	(*FindPathsRequest)(nil),         // 15: cortex.v1.FindPathsRequest
	(*PathsResponse)(nil),            // 16: cortex.v1.PathsResponse
	(*PathEntry)(nil),                // 17: cortex.v1.PathEntry
	(*NeighborhoodRequest)(nil),      // 18: cortex.v1.NeighborhoodRequest
	(*SimilaritySearchRequest)(nil),  // 19: cortex.v1.SimilaritySearchRequest
	(*SearchResponse)(nil),           // 20: cortex.v1.SearchResponse
	(*SearchResultEntry)(nil),        // 21: cortex.v1.SearchResultEntry
	(*HybridSearchRequest)(nil),      // 22: cortex.v1.HybridSearchRequest
	(*HybridSearchResponse)(nil),     // 23: cortex.v1.HybridSearchResponse
	(*HybridResultEntry)(nil),        // 24: cortex.v1.HybridResultEntry
	(*BriefingRequest)(nil),          // 25: cortex.v1.BriefingRequest
	(*BriefingResponse)(nil),         // 26: cortex.v1.BriefingResponse
	(*BriefingSection)(nil),          // 27: cortex.v1.BriefingSection
	(*StatsRequest)(nil),             // 28: cortex.v1.StatsRequest
	(*StatsResponse)(nil),            // 29: cortex.v1.StatsResponse
	(*AutoLinkerStatusRequest)(nil),  // 30: cortex.v1.AutoLinkerStatusRequest
	(*AutoLinkerStatusResponse)(nil), // 31: cortex.v1.AutoLinkerStatusResponse
	(*TriggerAutoLinkRequest)(nil),   // 32: cortex.v1.TriggerAutoLinkRequest
	(*TriggerAutoLinkResponse)(nil),  // 33: cortex.v1.TriggerAutoLinkResponse
	(*ReindexRequest)(nil),           // 34: cortex.v1.ReindexRequest
	(*ReindexResponse)(nil),          // 35: cortex.v1.ReindexResponse
	(*HealthRequest)(nil),            // 36: cortex.v1.HealthRequest
	(*HealthResponse)(nil),           // 37: cortex.v1.HealthResponse
	nil,                              // 38: cortex.v1.CreateNodeRequest.MetadataEntry
	nil,                              // 39: cortex.v1.UpdateNodeRequest.MetadataEntry
	nil,                              // 40: cortex.v1.NodeResponse.MetadataEntry
	nil,                              // 41: cortex.v1.SubgraphResponse.DepthsEntry
	nil,                              // 42: cortex.v1.StatsResponse.NodesByKindEntry
	nil,                              // 43: cortex.v1.StatsResponse.EdgesByRelationEntry
	(*timestamppb.Timestamp)(nil),    // 44: google.protobuf.Timestamp
}
var file_cortex_proto_depIdxs = []int32{
	38, // 0: cortex.v1.CreateNodeRequest.metadata:type_name -> cortex.v1.CreateNodeRequest.MetadataEntry
	39, // 1: cortex.v1.UpdateNodeRequest.metadata:type_name -> cortex.v1.UpdateNodeRequest.MetadataEntry
	7,  // 2: cortex.v1.ListNodesResponse.nodes:type_name -> cortex.v1.NodeResponse
	40, // 3: cortex.v1.NodeResponse.metadata:type_name -> cortex.v1.NodeResponse.MetadataEntry
	44, // 4: cortex.v1.NodeResponse.created_at:type_name -> google.protobuf.Timestamp
	44, // 5: cortex.v1.NodeResponse.updated_at:type_name -> google.protobuf.Timestamp
	44, // 6: cortex.v1.EdgeResponse.created_at:type_name -> google.protobuf.Timestamp
	44, // 7: cortex.v1.EdgeResponse.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 8: cortex.v1.GetEdgesResponse.edges:type_name -> cortex.v1.EdgeResponse
	7,  // 9: cortex.v1.SubgraphResponse.nodes:type_name -> cortex.v1.NodeResponse
	9,  // 10: cortex.v1.SubgraphResponse.edges:type_name -> cortex.v1.EdgeResponse
	41, // 11: cortex.v1.SubgraphResponse.depths:type_name -> cortex.v1.SubgraphResponse.DepthsEntry
	17, // 12: cortex.v1.PathsResponse.paths:type_name -> cortex.v1.PathEntry
	21, // 13: cortex.v1.SearchResponse.results:type_name -> cortex.v1.SearchResultEntry
	7,  // 14: cortex.v1.SearchResultEntry.node:type_name -> cortex.v1.NodeResponse
	24, // 15: cortex.v1.HybridSearchResponse.results:type_name -> cortex.v1.HybridResultEntry
	7,  // 16: cortex.v1.HybridResultEntry.node:type_name -> cortex.v1.NodeResponse
	27, // 17: cortex.v1.BriefingResponse.sections:type_name -> cortex.v1.BriefingSection
	7,  // 18: cortex.v1.BriefingSection.nodes:type_name -> cortex.v1.NodeResponse
	42, // 19: cortex.v1.StatsResponse.nodes_by_kind:type_name -> cortex.v1.StatsResponse.NodesByKindEntry
	43, // 20: cortex.v1.StatsResponse.edges_by_relation:type_name -> cortex.v1.StatsResponse.EdgesByRelationEntry
	44, // 21: cortex.v1.AutoLinkerStatusResponse.cursor:type_name -> google.protobuf.Timestamp
	29, // 22: cortex.v1.HealthResponse.stats:type_name -> cortex.v1.StatsResponse
	31, // 23: cortex.v1.HealthResponse.auto_linker:type_name -> cortex.v1.AutoLinkerStatusResponse
	0,  // 24: cortex.v1.CortexService.CreateNode:input_type -> cortex.v1.CreateNodeRequest
	1,  // 25: cortex.v1.CortexService.GetNode:input_type -> cortex.v1.GetNodeRequest
	2,  // 26: cortex.v1.CortexService.UpdateNode:input_type -> cortex.v1.UpdateNodeRequest
	3,  // 27: cortex.v1.CortexService.DeleteNode:input_type -> cortex.v1.DeleteNodeRequest
	5,  // 28: cortex.v1.CortexService.ListNodes:input_type -> cortex.v1.ListNodesRequest
	8,  // 29: cortex.v1.CortexService.CreateEdge:input_type -> cortex.v1.CreateEdgeRequest
	10, // 30: cortex.v1.CortexService.GetEdges:input_type -> cortex.v1.GetEdgesRequest
	12, // 31: cortex.v1.CortexService.DeleteEdge:input_type -> cortex.v1.DeleteEdgeRequest
	13, // 32: cortex.v1.CortexService.Traverse:input_type -> cortex.v1.TraverseRequest
	15, // 33: cortex.v1.CortexService.FindPaths:input_type -> cortex.v1.FindPathsRequest
	18, // 34: cortex.v1.CortexService.Neighborhood:input_type -> cortex.v1.NeighborhoodRequest
	19, // 35: cortex.v1.CortexService.SimilaritySearch:input_type -> cortex.v1.SimilaritySearchRequest
	22, // 36: cortex.v1.CortexService.HybridSearch:input_type -> cortex.v1.HybridSearchRequest
	25, // 37: cortex.v1.CortexService.GetBriefing:input_type -> cortex.v1.BriefingRequest
	28, // 38: cortex.v1.CortexService.Stats:input_type -> cortex.v1.StatsRequest
	30, // 39: cortex.v1.CortexService.AutoLinkerStatus:input_type -> cortex.v1.AutoLinkerStatusRequest
	32, // 40: cortex.v1.CortexService.TriggerAutoLink:input_type -> cortex.v1.TriggerAutoLinkRequest
	34, // 41: cortex.v1.CortexService.Reindex:input_type -> cortex.v1.ReindexRequest
	36, // 42: cortex.v1.CortexService.Health:input_type -> cortex.v1.HealthRequest
	7,  // 43: cortex.v1.CortexService.CreateNode:output_type -> cortex.v1.NodeResponse
	7,  // 44: cortex.v1.CortexService.GetNode:output_type -> cortex.v1.NodeResponse
	7,  // 45: cortex.v1.CortexService.UpdateNode:output_type -> cortex.v1.NodeResponse
	4,  // 46: cortex.v1.CortexService.DeleteNode:output_type -> cortex.v1.DeleteResponse
	6,  // 47: cortex.v1.CortexService.ListNodes:output_type -> cortex.v1.ListNodesResponse
	9,  // 48: cortex.v1.CortexService.CreateEdge:output_type -> cortex.v1.EdgeResponse
	11, // 49: cortex.v1.CortexService.GetEdges:output_type -> cortex.v1.GetEdgesResponse
	4,  // 50: cortex.v1.CortexService.DeleteEdge:output_type -> cortex.v1.DeleteResponse
	14, // 51: cortex.v1.CortexService.Traverse:output_type -> cortex.v1.SubgraphResponse
	16, // 52: cortex.v1.CortexService.FindPaths:output_type -> cortex.v1.PathsResponse
	14, // 53: cortex.v1.CortexService.Neighborhood:output_type -> cortex.v1.SubgraphResponse
	20, // 54: cortex.v1.CortexService.SimilaritySearch:output_type -> cortex.v1.SearchResponse
	23, // 55: cortex.v1.CortexService.HybridSearch:output_type -> cortex.v1.HybridSearchResponse
	26, // 56: cortex.v1.CortexService.GetBriefing:output_type -> cortex.v1.BriefingResponse
	29, // 57: cortex.v1.CortexService.Stats:output_type -> cortex.v1.StatsResponse
	31, // 58: cortex.v1.CortexService.AutoLinkerStatus:output_type -> cortex.v1.AutoLinkerStatusResponse
	33, // 59: cortex.v1.CortexService.TriggerAutoLink:output_type -> cortex.v1.TriggerAutoLinkResponse
	35, // 60: cortex.v1.CortexService.Reindex:output_type -> cortex.v1.ReindexResponse
	37, // 61: cortex.v1.CortexService.Health:output_type -> cortex.v1.HealthResponse
	43, // [43:62] is the sub-list for method output_type
	24, // [24:43] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_cortex_proto_init() }
func file_cortex_proto_init() {
	if File_cortex_proto != nil {
		return
	}
	file_cortex_proto_msgTypes[0].OneofWrappers = []any{}
	file_cortex_proto_msgTypes[2].OneofWrappers = []any{}
	file_cortex_proto_msgTypes[7].OneofWrappers = []any{}
	file_cortex_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortex_proto_rawDesc), len(file_cortex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortex_proto_goTypes,
		DependencyIndexes: file_cortex_proto_depIdxs,
		MessageInfos:      file_cortex_proto_msgTypes,
	}.Build()
	File_cortex_proto = out.File
	file_cortex_proto_goTypes = nil
	file_cortex_proto_depIdxs = nil
}
