// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: cortex.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CortexService_CreateNode_FullMethodName       = "/cortex.v1.CortexService/CreateNode"
	CortexService_GetNode_FullMethodName          = "/cortex.v1.CortexService/GetNode"
	CortexService_UpdateNode_FullMethodName       = "/cortex.v1.CortexService/UpdateNode"
	CortexService_DeleteNode_FullMethodName       = "/cortex.v1.CortexService/DeleteNode"
	CortexService_ListNodes_FullMethodName        = "/cortex.v1.CortexService/ListNodes"
	CortexService_CreateEdge_FullMethodName       = "/cortex.v1.CortexService/CreateEdge"
	CortexService_GetEdges_FullMethodName         = "/cortex.v1.CortexService/GetEdges"
	CortexService_DeleteEdge_FullMethodName       = "/cortex.v1.CortexService/DeleteEdge"
	CortexService_Traverse_FullMethodName         = "/cortex.v1.CortexService/Traverse"
	CortexService_FindPaths_FullMethodName        = "/cortex.v1.CortexService/FindPaths"
	CortexService_Neighborhood_FullMethodName     = "/cortex.v1.CortexService/Neighborhood"
	CortexService_SimilaritySearch_FullMethodName = "/cortex.v1.CortexService/SimilaritySearch"
	CortexService_HybridSearch_FullMethodName     = "/cortex.v1.CortexService/HybridSearch"
	CortexService_GetBriefing_FullMethodName      = "/cortex.v1.CortexService/GetBriefing"
	CortexService_Stats_FullMethodName            = "/cortex.v1.CortexService/Stats"
	CortexService_AutoLinkerStatus_FullMethodName = "/cortex.v1.CortexService/AutoLinkerStatus"
	CortexService_TriggerAutoLink_FullMethodName  = "/cortex.v1.CortexService/TriggerAutoLink"
	CortexService_Reindex_FullMethodName          = "/cortex.v1.CortexService/Reindex"
	CortexService_Health_FullMethodName           = "/cortex.v1.CortexService/Health"
)

// CortexServiceClient is the client API for CortexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CortexServiceClient interface {
	// Create a new knowledge node.
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	// Get a node by ID.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	// Update a node's content (triggers re-embedding).
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error)
	// Soft-delete a node.
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// List nodes with filtering.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Create a manual edge between two nodes.
	CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error)
	// Get edges for a node.
	GetEdges(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error)
	// Delete an edge.
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Traverse the graph from starting nodes.
	Traverse(ctx context.Context, in *TraverseRequest, opts ...grpc.CallOption) (*SubgraphResponse, error)
	// Find paths between two nodes.
	FindPaths(ctx context.Context, in *FindPathsRequest, opts ...grpc.CallOption) (*PathsResponse, error)
	// Get node neighborhood (convenience).
	Neighborhood(ctx context.Context, in *NeighborhoodRequest, opts ...grpc.CallOption) (*SubgraphResponse, error)
	// Semantic similarity search.
	SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Hybrid search (vector + graph proximity).
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
	// Get a synthesised context briefing for an agent.
	GetBriefing(ctx context.Context, in *BriefingRequest, opts ...grpc.CallOption) (*BriefingResponse, error)
	// Get graph statistics.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Get auto-linker metrics.
	AutoLinkerStatus(ctx context.Context, in *AutoLinkerStatusRequest, opts ...grpc.CallOption) (*AutoLinkerStatusResponse, error)
	// Trigger manual auto-linker cycle.
	TriggerAutoLink(ctx context.Context, in *TriggerAutoLinkRequest, opts ...grpc.CallOption) (*TriggerAutoLinkResponse, error)
	// Reindex all embeddings (model change).
	Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*ReindexResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cortexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCortexServiceClient(cc grpc.ClientConnInterface) CortexServiceClient {
	return &cortexServiceClient{cc}
}

func (c *cortexServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, CortexService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, CortexService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, CortexService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CortexService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, CortexService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) CreateEdge(ctx context.Context, in *CreateEdgeRequest, opts ...grpc.CallOption) (*EdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EdgeResponse)
	err := c.cc.Invoke(ctx, CortexService_CreateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) GetEdges(ctx context.Context, in *GetEdgesRequest, opts ...grpc.CallOption) (*GetEdgesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgesResponse)
	err := c.cc.Invoke(ctx, CortexService_GetEdges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CortexService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) Traverse(ctx context.Context, in *TraverseRequest, opts ...grpc.CallOption) (*SubgraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubgraphResponse)
	err := c.cc.Invoke(ctx, CortexService_Traverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) FindPaths(ctx context.Context, in *FindPathsRequest, opts ...grpc.CallOption) (*PathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathsResponse)
	err := c.cc.Invoke(ctx, CortexService_FindPaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) Neighborhood(ctx context.Context, in *NeighborhoodRequest, opts ...grpc.CallOption) (*SubgraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubgraphResponse)
	err := c.cc.Invoke(ctx, CortexService_Neighborhood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, CortexService_SimilaritySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, CortexService_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) GetBriefing(ctx context.Context, in *BriefingRequest, opts ...grpc.CallOption) (*BriefingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BriefingResponse)
	err := c.cc.Invoke(ctx, CortexService_GetBriefing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, CortexService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) AutoLinkerStatus(ctx context.Context, in *AutoLinkerStatusRequest, opts ...grpc.CallOption) (*AutoLinkerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoLinkerStatusResponse)
	err := c.cc.Invoke(ctx, CortexService_AutoLinkerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) TriggerAutoLink(ctx context.Context, in *TriggerAutoLinkRequest, opts ...grpc.CallOption) (*TriggerAutoLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerAutoLinkResponse)
	err := c.cc.Invoke(ctx, CortexService_TriggerAutoLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) Reindex(ctx context.Context, in *ReindexRequest, opts ...grpc.CallOption) (*ReindexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReindexResponse)
	err := c.cc.Invoke(ctx, CortexService_Reindex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CortexService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CortexServiceServer is the server API for CortexService service.
// All implementations must embed UnimplementedCortexServiceServer
// for forward compatibility.
type CortexServiceServer interface {
	// Create a new knowledge node.
	CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error)
	// Get a node by ID.
	GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error)
	// Update a node's content (triggers re-embedding).
	UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error)
	// Soft-delete a node.
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteResponse, error)
	// List nodes with filtering.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Create a manual edge between two nodes.
	CreateEdge(context.Context, *CreateEdgeRequest) (*EdgeResponse, error)
	// Get edges for a node.
	GetEdges(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error)
	// Delete an edge.
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteResponse, error)
	// Traverse the graph from starting nodes.
	Traverse(context.Context, *TraverseRequest) (*SubgraphResponse, error)
	// Find paths between two nodes.
	FindPaths(context.Context, *FindPathsRequest) (*PathsResponse, error)
	// Get node neighborhood (convenience).
	Neighborhood(context.Context, *NeighborhoodRequest) (*SubgraphResponse, error)
	// Semantic similarity search.
	SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SearchResponse, error)
	// Hybrid search (vector + graph proximity).
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
	// Get a synthesised context briefing for an agent.
	GetBriefing(context.Context, *BriefingRequest) (*BriefingResponse, error)
	// Get graph statistics.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Get auto-linker metrics.
	AutoLinkerStatus(context.Context, *AutoLinkerStatusRequest) (*AutoLinkerStatusResponse, error)
	// Trigger manual auto-linker cycle.
	TriggerAutoLink(context.Context, *TriggerAutoLinkRequest) (*TriggerAutoLinkResponse, error)
	// Reindex all embeddings (model change).
	Reindex(context.Context, *ReindexRequest) (*ReindexResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedCortexServiceServer()
}

// UnimplementedCortexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCortexServiceServer struct{}

func (UnimplementedCortexServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedCortexServiceServer) GetNode(context.Context, *GetNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedCortexServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedCortexServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedCortexServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedCortexServiceServer) CreateEdge(context.Context, *CreateEdgeRequest) (*EdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdge not implemented")
}
func (UnimplementedCortexServiceServer) GetEdges(context.Context, *GetEdgesRequest) (*GetEdgesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdges not implemented")
}
func (UnimplementedCortexServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedCortexServiceServer) Traverse(context.Context, *TraverseRequest) (*SubgraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Traverse not implemented")
}
func (UnimplementedCortexServiceServer) FindPaths(context.Context, *FindPathsRequest) (*PathsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPaths not implemented")
}
func (UnimplementedCortexServiceServer) Neighborhood(context.Context, *NeighborhoodRequest) (*SubgraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Neighborhood not implemented")
}
func (UnimplementedCortexServiceServer) SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimilaritySearch not implemented")
}
func (UnimplementedCortexServiceServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedCortexServiceServer) GetBriefing(context.Context, *BriefingRequest) (*BriefingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBriefing not implemented")
}
func (UnimplementedCortexServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedCortexServiceServer) AutoLinkerStatus(context.Context, *AutoLinkerStatusRequest) (*AutoLinkerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoLinkerStatus not implemented")
}
func (UnimplementedCortexServiceServer) TriggerAutoLink(context.Context, *TriggerAutoLinkRequest) (*TriggerAutoLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerAutoLink not implemented")
}
func (UnimplementedCortexServiceServer) Reindex(context.Context, *ReindexRequest) (*ReindexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedCortexServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCortexServiceServer) mustEmbedUnimplementedCortexServiceServer() {}
func (UnimplementedCortexServiceServer) testEmbeddedByValue()                       {}

// UnsafeCortexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CortexServiceServer will
// result in compilation errors.
type UnsafeCortexServiceServer interface {
	mustEmbedUnimplementedCortexServiceServer()
}

func RegisterCortexServiceServer(s grpc.ServiceRegistrar, srv CortexServiceServer) {
	// If the following call panics, it indicates UnimplementedCortexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CortexService_ServiceDesc, srv)
}

func _CortexService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_CreateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).CreateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_CreateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).CreateEdge(ctx, req.(*CreateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_GetEdges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).GetEdges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_GetEdges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).GetEdges(ctx, req.(*GetEdgesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_Traverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Traverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Traverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Traverse(ctx, req.(*TraverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_FindPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).FindPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_FindPaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).FindPaths(ctx, req.(*FindPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_Neighborhood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeighborhoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Neighborhood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Neighborhood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Neighborhood(ctx, req.(*NeighborhoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_SimilaritySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilaritySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).SimilaritySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_SimilaritySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).SimilaritySearch(ctx, req.(*SimilaritySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_GetBriefing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BriefingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).GetBriefing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_GetBriefing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).GetBriefing(ctx, req.(*BriefingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_AutoLinkerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoLinkerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).AutoLinkerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_AutoLinkerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).AutoLinkerStatus(ctx, req.(*AutoLinkerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_TriggerAutoLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerAutoLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).TriggerAutoLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_TriggerAutoLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).TriggerAutoLink(ctx, req.(*TriggerAutoLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Reindex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Reindex(ctx, req.(*ReindexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CortexService_ServiceDesc is the grpc.ServiceDesc for CortexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CortexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortex.v1.CortexService",
	HandlerType: (*CortexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _CortexService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _CortexService_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _CortexService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _CortexService_DeleteNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _CortexService_ListNodes_Handler,
		},
		{
			MethodName: "CreateEdge",
			Handler:    _CortexService_CreateEdge_Handler,
		},
		{
			MethodName: "GetEdges",
			Handler:    _CortexService_GetEdges_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _CortexService_DeleteEdge_Handler,
		},
		{
			MethodName: "Traverse",
			Handler:    _CortexService_Traverse_Handler,
		},
		{
			MethodName: "FindPaths",
			Handler:    _CortexService_FindPaths_Handler,
		},
		{
			MethodName: "Neighborhood",
			Handler:    _CortexService_Neighborhood_Handler,
		},
		{
			MethodName: "SimilaritySearch",
			Handler:    _CortexService_SimilaritySearch_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _CortexService_HybridSearch_Handler,
		},
		{
			MethodName: "GetBriefing",
			Handler:    _CortexService_GetBriefing_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _CortexService_Stats_Handler,
		},
		{
			MethodName: "AutoLinkerStatus",
			Handler:    _CortexService_AutoLinkerStatus_Handler,
		},
		{
			MethodName: "TriggerAutoLink",
			Handler:    _CortexService_TriggerAutoLink_Handler,
		},
		{
			MethodName: "Reindex",
			Handler:    _CortexService_Reindex_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _CortexService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortex.proto",
}
